# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localgcp < Formula
  desc "The unified GCP emulator. One binary, thirteen services, zero cloud bills."
  homepage "https://localgcp.com"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slokam-ai/localgcp/releases/download/v0.6.0/localgcp_0.6.0_darwin_amd64.tar.gz"
      sha256 "abdb9cbb362eb972344a6d4af214b1d9ef3a88ff94a7621b172a8f16fa4505bc"

      define_method(:install) do
        bin.install "localgcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slokam-ai/localgcp/releases/download/v0.6.0/localgcp_0.6.0_darwin_arm64.tar.gz"
      sha256 "614351866baecbf4e99bb29d62d4b24e1f6106391cbcde619bf50a661bce0aff"

      define_method(:install) do
        bin.install "localgcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slokam-ai/localgcp/releases/download/v0.6.0/localgcp_0.6.0_linux_amd64.tar.gz"
      sha256 "7cd5937c7c3856675f4180ced40bd4278db03b5607389a63d1e86502a3131cd4"
      define_method(:install) do
        bin.install "localgcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slokam-ai/localgcp/releases/download/v0.6.0/localgcp_0.6.0_linux_arm64.tar.gz"
      sha256 "0b6c2dc884411f150a5e40f19c865d167d6e939f908604b9c5abcd6b09ff37f0"
      define_method(:install) do
        bin.install "localgcp"
      end
    end
  end

  test do
    system bin/"localgcp", "--version"
  end
end
