# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localgcp < Formula
  desc "The unified GCP emulator. One binary, thirteen services, zero cloud bills."
  homepage "https://localgcp.com"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slokam-ai/localgcp/releases/download/v0.5.1/localgcp_0.5.1_darwin_amd64.tar.gz"
      sha256 "e86ce04c8de1aff5dfe60d37bc4a198a9e47d298df1ab85303eb0bb39741ffa2"

      define_method(:install) do
        bin.install "localgcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slokam-ai/localgcp/releases/download/v0.5.1/localgcp_0.5.1_darwin_arm64.tar.gz"
      sha256 "6effe4395ce1d96f26f5ee65db44b759f21fb26a20de1c44f4fe9927869d78e9"

      define_method(:install) do
        bin.install "localgcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slokam-ai/localgcp/releases/download/v0.5.1/localgcp_0.5.1_linux_amd64.tar.gz"
      sha256 "54beb9381651497271e4b35125970c025d4427801c9dae22951e0eb4714e8fbf"
      define_method(:install) do
        bin.install "localgcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slokam-ai/localgcp/releases/download/v0.5.1/localgcp_0.5.1_linux_arm64.tar.gz"
      sha256 "459e1b0413f9706be359aa842b053b539e54906f175fc31303a60a3895b337b9"
      define_method(:install) do
        bin.install "localgcp"
      end
    end
  end

  test do
    system bin/"localgcp", "--version"
  end
end
