# This file was generated by GoReleaser. DO NOT EDIT.
cask "localgcp" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_darwin_amd64.tar.gz"
      sha256 "52c4a79ae52432e6ceabeb33f5f56aa08f83308758296eea15346f13fa127339"
    end
    on_arm do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_darwin_arm64.tar.gz"
      sha256 "99cf0301098036afa70e9b2af78dbd998ac2bbdb44a1c9dfa25c784e0454f07d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_linux_amd64.tar.gz"
      sha256 "1646fc3f64f9dee61c9e2e76480672b3f8cffa78a6b31c49902bc63f25c7ef4b"
    end
    on_arm do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_linux_arm64.tar.gz"
      sha256 "a0bea50fb925be16063a8b723a55adcd159c41925c01bc4f88fb6ebb5d13f177"
    end
  end

  name "localgcp"
  desc "The first unified GCP emulator. One binary, five services, zero cloud bills."
  homepage "https://localgcp.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localgcp"

  # No zap stanza required

end
