# This file was generated by GoReleaser. DO NOT EDIT.
cask "localgcp" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_darwin_amd64.tar.gz"
      sha256 "31e7662b31f0fbbf45a7cb3012bae02a70eb130bce0aca92ddc7b130a37aca27"
    end
    on_arm do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_darwin_arm64.tar.gz"
      sha256 "e483e83208d02411c13db5e218e78ddb4614560573cd8845211ee20559580194"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_linux_amd64.tar.gz"
      sha256 "f2a1c81f2aaffaa9cd858148ae85fb49e5100a4ff89113c9d77ad48e94baa42b"
    end
    on_arm do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_linux_arm64.tar.gz"
      sha256 "cea20453c61dd4f365351348f7be4ebcc563a779ef26657d789dd7445e42f5e3"
    end
  end

  name "localgcp"
  desc "The first unified GCP emulator. One binary, five services, zero cloud bills."
  homepage "https://localgcp.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localgcp"

  # No zap stanza required

end
