# This file was generated by GoReleaser. DO NOT EDIT.
cask "localgcp" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_darwin_amd64.tar.gz"
      sha256 "a36d6d55043e4f14006c8607d03a8ccc0701af5fdade8925aba58f7688846ff2"
    end
    on_arm do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_darwin_arm64.tar.gz"
      sha256 "011cfba70b535b091a2ea343faa91b170bad3432b19127adc70ebe87f28df395"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_linux_amd64.tar.gz"
      sha256 "e09e7b95129e66ba88b11b35af93c227a9d384b42cb3a4e3c7cdaf912a8f53c3"
    end
    on_arm do
      url "https://github.com/slokam-ai/localgcp/releases/download/v#{version}/localgcp_#{version}_linux_arm64.tar.gz"
      sha256 "e4f03dcd5617388e876dd2591ca5d6ab1be200aade829080797b162688d90b63"
    end
  end

  name "localgcp"
  desc "The first unified GCP emulator. One binary, five services, zero cloud bills."
  homepage "https://localgcp.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localgcp"

  # No zap stanza required

end
